#
###################################
# Site wide configuration
####################################
#
title: Minjoon Kim
email: minjoon.kim89@gmail.com
description: Minjoon's blog.
url: https://minjoon.kim # the base hostname & protocol for your site
keywords: ["HCI/UX", "Data Design for Personalization", "Ultimate"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Minjoon
  avatar: avatar.jpg
  job: "Ph.D Student at Seoul National University"
  bio: "#ux #pref_elicitation #data #ultimate"
  email: minjoon.kim89@gmail.com
  disqus-shortname: mjblog-3
  twitter: ns9mj #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-45185383-2
    verify: zDcCrM3fLOB1u7jLSTLPnNf-a2RjHX_henj7qKgRFZ4
    ad-client:
    ad-slot:
  bing-verify:
  github: minjoonkim #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: minjoonkim10 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
